(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ac-auto-show-menu 0.2)
 '(ac-modes
   (quote
	(emacs-lisp-mode lisp-interaction-mode c-mode cc-mode java-mode clojure-mode python-mode ruby-mode javascript-mode js2-mode css-mode sh-mode xml-mode sgml-mode sql-mode)))
 '(ac-quick-help-delay 0.6)
 '(ac-use-menu-map t)
 '(ansi-color-names-vector
   ["#242424" "#e5786d" "#95e454" "#cae682" "#8ac6f2" "#333366" "#ccaa8f" "#f6f3e8"])
 '(blink-cursor-mode nil)
 '(comment-auto-fill-only-comments t)
 '(custom-enabled-themes (quote (wombat)))
 '(debug-on-error t)
 '(delete-selection-mode t)
 '(dired-auto-revert-buffer (quote dired-directory-changed-p))
 '(dired-isearch-filenames (quote dwim))
 '(dired-listing-switches "-alGh --group-directories-first")
 '(dired-recursive-copies (quote always))
 '(ecb-options-version "2.40")
 '(eol-mnemonic-mac "(Mac)")
 '(grep-command "grep -nH --extended-regexp -e ")
 '(grep-files-aliases
   (quote
	(("all" . "* .*")
	 ("el" . "*.el")
	 ("c" . "*.[ch]")
	 ("rb" . "*.rb *.erb Rakefile Capfile Gemfile *.ru")
	 ("js" . "*.js")
	 ("lisp" . "*.lisp *.el")
	 ("java" . "*.java"))))
 '(grep-highlight-matches (quote auto))
 '(grep-scroll-output t)
 '(ido-auto-merge-work-directories-length -1)
 '(ido-enable-flex-matching t)
 '(ido-enable-regexp t)
 '(ido-mode (quote both) nil (ido))
 '(inhibit-startup-screen t)
 '(initial-major-mode (quote emacs-lisp-mode))
 '(initial-scratch-message "")
 '(ispell-check-comments (quote exclusive))
 '(ispell-dictionary "british")
 '(js2-allow-rhino-new-expr-initializer nil)
 '(js2-auto-indent-p t)
 '(js2-include-gears-externs nil)
 '(js2-include-rhino-externs nil)
 '(js2-mirror-mode t)
 '(js2-rebind-eol-bol-keys nil)
 '(kill-do-not-save-duplicates t)
 '(kill-whole-line t)
 '(major-mode (quote markdown-mode))
 '(make-backup-files nil)
 '(mark-even-if-inactive t)
 '(markdown-command "marked")
 '(nxml-auto-insert-xml-declaration-flag t)
 '(nxml-slash-auto-complete-flag t)
 '(org-agenda-files
   (quote
	("~/repos/org/english.org" "~/repos/org/programming.org")))
 '(python-shell-virtualenv-path "C:\\Python27\\Scripts\\virtualenv.exe")
 '(reb-re-syntax (quote string))
 '(ruler-mode-inter-graduation-char 58)
 '(safe-local-variable-values (quote ((encoding . utf-8))))
 '(scroll-bar-mode (quote right))
 '(show-paren-mode t)
 '(sql-electric-stuff (quote semicolon))
 '(sql-port 5432)
 '(sql-product (quote oracle))
 '(sql-user "bart")
 '(tab-width 4)
 '(tool-bar-mode nil)
 '(track-eol t)
 '(tramp-default-method "ssh")
 '(tramp-encoding-shell "/bin/zsh")
 '(wdired-allow-to-change-permissions t)
 '(word-wrap t)
 '(yas-wrap-around-region t)
 '(yas/ignore-filenames-as-triggers t)
 '(zencoding-preview-default nil))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:height 130 :family "Source Code Pro"))))
 '(isearch ((t (:background "dark orange" :foreground "white"))))
 '(isearch-fail ((t (:background "red" :foreground "white"))))
 '(lazy-highlight ((t (:background "gold"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "steel blue"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "pale goldenrod"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "turquoise"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "salmon"))))
 '(ruler-mode-comment-column ((t (:inherit ruler-mode-default :foreground "black"))) t)
 '(ruler-mode-current-column ((t (:inherit ruler-mode-default :foreground "black" :weight bold))) t)
 '(ruler-mode-default ((t (:inherit default :background "gray93" :foreground "grey64" :box (:line-width 1 :color "grey76" :style released-button)))) t)
 '(ruler-mode-fill-column ((t (:inherit ruler-mode-default :foreground "black"))) t)
 '(ruler-mode-pad ((t (:inherit ruler-mode-default :background "grey93"))) t))
